### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by alexyy802**
Added a notice to uninstall fork's or discord.py before installing texus

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by alexyy802** [comment]
If any spelling mistakes please tell me :D

**Review by VincentRPS — APPROVED** [review]
lgtm

**Comment by VincentRPS** [comment]
@alexyy802 when making commits next time please use https://www.conventionalcommits.org/en/v1.0.0/

**Comment by alexyy802** [comment]
Alrighty

**Pull request merged**
